
CREATE ROLE readonly WITH LOGIN PASSWORD 'read' 
NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';

GRANT CONNECT ON DATABASE "dvdrental" TO readonly;
GRANT USAGE ON SCHEMA public TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO readonly;


REVOKE ALL PRIVILEGES ON ALL SEQUENCES  IN SCHEMA public  FROM readonly;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public  FROM readonly;
REVOKE ALL PRIVILEGES ON SCHEMA public  FROM readonly;
REVOKE ALL PRIVILEGES ON DATABASE "dvdrental" FROM readonly;

-- DROP ROLE  readonly ;


CREATE ROLE userpgm WITH LOGIN PASSWORD 'usrpgm' 
NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';

GRANT CONNECT ON DATABASE "dvdrental" TO userpgm;
GRANT USAGE ON SCHEMA public TO userpgm;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO userpgm;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO userpgm;
GRANT UPDATE ON ALL TABLES IN SCHEMA public TO userpgm;
GRANT DELETE ON ALL TABLES IN SCHEMA public TO userpgm;
GRANT UPDATE ON ALL TABLES IN SCHEMA public TO userpgm;
GRANT INSERT ON ALL TABLES IN SCHEMA public TO userpgm;
GRANT TEMPORARY ON DATABASE "dvdrental"  TO userpgm;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES  IN SCHEMA public  FROM userpgm;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public  FROM userpgm;
REVOKE ALL PRIVILEGES ON SCHEMA public  FROM userpgm;
REVOKE ALL PRIVILEGES ON DATABASE "dvdrental" FROM userpgm;

-- DROP ROLE  userpgm ;
